import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import React from "react";
import NavBar from "@/components/NavBar";
import { Spacer } from "@nextui-org/spacer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-dvh w-dvw flex flex-col items-center justify-center">
        <Providers>
          <NavBar />
          <Spacer y={2} />
          <div className="container flex flex-col px-4 grow mb-4">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
