import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import React from "react";
import NavBar from "@/components/NavBar";
import { Spacer } from "@nextui-org/spacer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          <Spacer y={2} />
          <main className="container flex justify-center px-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
